import { ENTRY_COST } from './constants';
import type { GameConfig } from '../types/models';

export const GAMES: GameConfig[] = [
  {
    id: 'speed-tapper',
    slug: 'speed-tapper',
    name: 'Blade Master',
    tagline: 'Aim. Throw. Hit perfect.',
    description:
      'Take aim at the wooden target, throw your blades with precision and build a high score across every stage.',
    guide: [
      'Aim for the target and throw blades into open sections.',
      'Land accurate hits to build your score and combo.',
      'Avoid blades already stuck in the target.',
      'Entry costs 20 Tokens. A revive costs 10 Tokens and adds extra time.',
    ],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#e8a317',
    accentSoft: '#fff1cc',
    art: 'tap',
  },
  {
    id: 'memory-match',
    slug: 'memory-match',
    name: 'Nut Craft',
    tagline: 'Twist. Remove. Master.',
    description:
      'Solve colorful mechanical puzzles by removing screws, matching pieces and clearing each crafted board.',
    guide: [
      'Study the board and identify which fasteners should move first.',
      'Remove pieces in the right order to open the puzzle.',
      'Plan ahead so one piece does not block the next move.',
      'Entry costs 20 Tokens. Revive restores time and keeps your progress.',
    ],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#5b6cff',
    accentSoft: '#e8ebff',
    art: 'memory',
  },
  {
    id: 'number-rush',
    slug: 'number-rush',
    name: 'Bowlexa',
    tagline: 'Aim. Swing. Strike.',
    description:
      'Roll the perfect bowling ball, knock down every pin and chase bigger strikes through a bright arcade lane.',
    guide: [
      'Aim your shot toward the pins before you swing.',
      'Time the release to send the ball down the lane.',
      'Strikes and clean clears bring the highest scores.',
      'Entry costs 20 Tokens. Revive adds extra seconds.',
    ],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#12a37a',
    accentSoft: '#d9f6ec',
    art: 'numbers',
  },
  {
    id: 'color-reflex',
    slug: 'color-reflex',
    name: 'Block Crush',
    tagline: 'Aim. Crush. Repeat.',
    description:
      'Launch the ball into numbered blocks, clear the board and collect powerful boosts as the levels get harder.',
    guide: [
      'Aim the ball to hit as many numbered blocks as possible.',
      'Break blocks before their numbers reach the paddle.',
      'Collect multi-ball, shield and power-up bonuses when they appear.',
      'Entry costs 20 Tokens. Accuracy heavily affects Game Coins.',
    ],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#e34d8b',
    accentSoft: '#ffe0ee',
    art: 'color',
  },
  {
    id: 'catch-the-coin',
    slug: 'catch-the-coin',
    name: 'Slice Storm',
    tagline: 'Slice. Combo. Conquer.',
    description:
      'Slice flying fruit with perfect timing, chain colorful combos and earn bigger rewards with every clean cut.',
    guide: [
      'Swipe through the fruit as it flies across the screen.',
      'Chain multiple slices together to build a combo.',
      'Stay precise and avoid missing fast-moving fruit.',
      'Entry costs 20 Tokens. Revive keeps your streak alive.',
    ],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#c9a227',
    accentSoft: '#fff4cc',
    art: 'coin',
  },
  {
    id: 'pulse-runner',
    slug: 'pulse-runner',
    name: 'Cosmo Warrior',
    tagline: 'Fight. Survive. Save the galaxy.',
    description: 'Pilot a powerful spaceship, defeat waves of alien invaders and protect the galaxy from destruction.',
    guide: ['Coming soon.'],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#3ec6ff',
    accentSoft: '#d7f4ff',
    art: 'runner',
  },
  {
    id: 'neon-maze',
    slug: 'neon-maze',
    name: 'Toilet Tactics',
    tagline: 'Flush. Fight. Survive. Win.',
    description: 'Defend the city from a ridiculous toilet invasion, upgrade your weapons and survive every attack wave.',
    guide: ['Coming soon.'],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#7c5cff',
    accentSoft: '#ece6ff',
    art: 'maze',
  },
  {
    id: 'orbit-puzzle',
    slug: 'orbit-puzzle',
    name: 'Word Hunt',
    tagline: 'Find words. Win rewards.',
    description: 'Search colorful letter grids for hidden words, sharpen your vocabulary and complete each challenge.',
    guide: ['Coming soon.'],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#4f8cff',
    accentSoft: '#dce9ff',
    art: 'orbit',
  },
  {
    id: 'storm-strike',
    slug: 'storm-strike',
    name: 'Bubble Blast Legend',
    tagline: 'Aim. Shoot. Pop. Win.',
    description: 'Fire colorful bubbles from the cannon, match groups, clear levels and unleash powerful boosters.',
    guide: ['Coming soon.'],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#6ecbff',
    accentSoft: '#def4ff',
    art: 'storm',
  },
  {
    id: 'echo-beat',
    slug: 'echo-beat',
    name: 'Merge Master',
    tagline: 'Merge blocks. Score big. Win.',
    description: 'Combine matching numbered blocks, create bigger values and chase your best score on the grid.',
    guide: ['Coming soon.'],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#ff6b6b',
    accentSoft: '#ffe1e1',
    art: 'beat',
  },
  {
    id: 'vault-breaker',
    slug: 'vault-breaker',
    name: 'Wormzy',
    tagline: 'Eat apples. Solve puzzles. Win.',
    description: 'Guide a cheerful worm through clever paths, collect the apple and solve every block puzzle.',
    guide: [
      'Tap the arrow buttons to move the worm around the grid.',
      'Eat the red apple to grow longer and score points.',
      'Avoid the walls and your own tail — hitting them costs a move.',
      'Each apple adds a new wall every two levels. Entry costs 20 Tokens.',
    ],
    entryCost: ENTRY_COST,
    status: 'playable',
    accent: '#b08d57',
    accentSoft: '#f3e7d3',
    art: 'vault',
  },
  {
    id: 'prism-drift',
    slug: 'prism-drift',
    name: 'Aqua Fill',
    tagline: 'Draw. Fill. Make happy.',
    description: 'Draw a smart path for the water, fill the glass and earn three stars on every puzzle.',
    guide: [
      'Tap the blue water source to start drawing a path.',
      'Tap adjacent cells to extend the path toward the glass.',
      'Reach the glass to fill it and score a point.',
      'Avoid walls — a wrong tap resets your path. Entry costs 20 Tokens.',
    ],
    entryCost: ENTRY_COST,
    status: 'playable',
    accent: '#2ec4b6',
    accentSoft: '#d4f7f3',
    art: 'prism',
  },
  {
    id: 'titan-trail',
    slug: 'titan-trail',
    name: 'Realm Clash',
    tagline: 'Build. Battle. Conquer.',
    description:
      'Command colorful armies, capture the central tower and conquer the rival realm with smart strategy.',
    guide: ['Coming soon.'],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#d96c3b',
    accentSoft: '#ffe3d4',
    art: 'titan',
  },
];

export function getGameBySlug(slug: string): GameConfig | undefined {
  return GAMES.find((game) => game.slug === slug);
}

export const PLAYABLE_SLUGS = GAMES.filter((game) => game.status === 'playable').map(
  (game) => game.slug,
);
