import { ENTRY_COST } from './constants';
import type { GameConfig } from '../types/models';

export const GAMES: GameConfig[] = [
  {
    id: 'speed-tapper',
    slug: 'speed-tapper',
    name: 'Blade Master',
    tagline: 'Aim. Throw. Hit perfect.',
    description:
      'Take aim at the wooden target, throw your blades with precision and build a high score across every stage.',
    guide: [
      'Aim for the target and throw blades into open sections.',
      'Land accurate hits to build your score and combo.',
      'Avoid blades already stuck in the target.',
      'Entry costs 20 Tokens. A revive costs 10 Tokens and adds extra time.',
    ],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#e8a317',
    accentSoft: '#fff1cc',
    art: 'tap',
  },
  {
    id: 'memory-match',
    slug: 'memory-match',
    name: 'Nut Craft',
    tagline: 'Twist. Remove. Master.',
    description:
      'Solve colorful mechanical puzzles by removing screws, matching pieces and clearing each crafted board.',
    guide: [
      'Study the board and identify which fasteners should move first.',
      'Remove pieces in the right order to open the puzzle.',
      'Plan ahead so one piece does not block the next move.',
      'Entry costs 20 Tokens. Revive restores time and keeps your progress.',
    ],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#5b6cff',
    accentSoft: '#e8ebff',
    art: 'memory',
  },
  {
    id: 'number-rush',
    slug: 'number-rush',
    name: 'Bowlexa',
    tagline: 'Aim. Swing. Strike.',
    description:
      'Roll the perfect bowling ball, knock down every pin and chase bigger strikes through a bright arcade lane.',
    guide: [
      'Aim your shot toward the pins before you swing.',
      'Time the release to send the ball down the lane.',
      'Strikes and clean clears bring the highest scores.',
      'Entry costs 20 Tokens. Revive adds extra seconds.',
    ],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#12a37a',
    accentSoft: '#d9f6ec',
    art: 'numbers',
  },
  {
    id: 'color-reflex',
    slug: 'color-reflex',
    name: 'Block Crush',
    tagline: 'Aim. Crush. Repeat.',
    description:
      'Launch the ball into numbered blocks, clear the board and collect powerful boosts as the levels get harder.',
    guide: [
      'Aim the ball to hit as many numbered blocks as possible.',
      'Break blocks before their numbers reach the paddle.',
      'Collect multi-ball, shield and power-up bonuses when they appear.',
      'Entry costs 20 Tokens. Accuracy heavily affects Game Coins.',
    ],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#e34d8b',
    accentSoft: '#ffe0ee',
    art: 'color',
  },
  {
    id: 'catch-the-coin',
    slug: 'catch-the-coin',
    name: 'Slice Storm',
    tagline: 'Slice. Combo. Conquer.',
    description:
      'Slice flying fruit with perfect timing, chain colorful combos and earn bigger rewards with every clean cut.',
    guide: [
      'Swipe through the fruit as it flies across the screen.',
      'Chain multiple slices together to build a combo.',
      'Stay precise and avoid missing fast-moving fruit.',
      'Entry costs 20 Tokens. Revive keeps your streak alive.',
    ],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#c9a227',
    accentSoft: '#fff4cc',
    art: 'coin',
  },
  {
    id: 'pulse-runner',
    slug: 'pulse-runner',
    name: 'Cosmo Warrior',
    tagline: 'Fight. Survive. Save the galaxy.',
    description: 'Pilot a powerful spaceship, defeat waves of alien invaders and protect the galaxy from destruction.',
    guide: ['Coming soon.'],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#3ec6ff',
    accentSoft: '#d7f4ff',
    art: 'runner',
  },
  {
    id: 'neon-maze',
    slug: 'neon-maze',
    name: 'Toilet Tactics',
    tagline: 'Flush. Fight. Survive. Win.',
    description: 'Defend the city from a ridiculous toilet invasion, upgrade your weapons and survive every attack wave.',
    guide: ['Coming soon.'],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#7c5cff',
    accentSoft: '#ece6ff',
    art: 'maze',
  },
  {
    id: 'orbit-puzzle',
    slug: 'orbit-puzzle',
    name: 'Word Hunt',
    tagline: 'Find words. Win rewards.',
    description: 'Search colorful letter grids for hidden words, sharpen your vocabulary and complete each challenge.',
    guide: ['Coming soon.'],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#4f8cff',
    accentSoft: '#dce9ff',
    art: 'orbit',
  },
  {
    id: 'storm-strike',
    slug: 'storm-strike',
    name: 'Bubble Blast Legend',
    tagline: 'Aim. Shoot. Pop. Win.',
    description: 'Fire colorful bubbles from the cannon, match groups, clear levels and unleash powerful boosters.',
    guide: ['Coming soon.'],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#6ecbff',
    accentSoft: '#def4ff',
    art: 'storm',
  },
  {
    id: 'echo-beat',
    slug: 'echo-beat',
    name: 'Merge Master',
    tagline: 'Merge blocks. Score big. Win.',
    description: 'Combine matching numbered blocks, create bigger values and chase your best score on the grid.',
    guide: ['Coming soon.'],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#ff6b6b',
    accentSoft: '#ffe1e1',
    art: 'beat',
  },
  {
    id: 'vault-breaker',
    slug: 'vault-breaker',
    name: 'Wormzy',
    tagline: 'Eat apples. Solve puzzles. Win.',
    description: 'Guide a cheerful worm through clever paths, collect the apple and solve every block puzzle.',
    guide: [
      'Move Wormzy one cell at a time with the arrow keys, W A S D, the on-screen pad, or by tapping a neighbouring cell.',
      'Start at the top-left cell and reach the glowing goal cell in the bottom-right corner.',
      'Every level gives you exactly 10 seconds — the timer resets each time you clear a level.',
      'Stones block the way. Bumping into one keeps Wormzy where it is, so find another route around them.',
      'Bombs are instant game over: one wrong step ends the whole run.',
      'Clear 15 levels for the Diamond prize. Silver and Gold unlock as you progress. Entry costs 20 Tokens.',
    ],
    entryCost: ENTRY_COST,
    status: 'playable',
    accent: '#b08d57',
    accentSoft: '#f3e7d3',
    art: 'vault',
  },
  {
    id: 'prism-drift',
    slug: 'prism-drift',
    name: 'Aqua Fill',
    tagline: 'Draw. Fill. Make happy.',
    description:
      'Draw a line from the water pipe into the glass, slip around stones, pillars and walls, and fill the glass past its target line before the timer runs out.',
    guide: [
      'Press on the water pipe and drag to draw your line. It works with a mouse, a finger or a pen.',
      'Finish the line on the glass to let the water flow. Short lines arrive with more water, so stay close to the best route.',
      'Drag back over your line to undo a step, or use "Reset path" to clear it and try again.',
      'Water cannot pass through stones, pillars, blocks or walls — route around them.',
      'Every level has 10 seconds (15 seconds from level 11) and the glass target rises as you progress.',
      'Entry costs 20 Tokens. Clear 20 levels for the Diamond prize.',
    ],
    entryCost: ENTRY_COST,
    status: 'playable',
    accent: '#2ec4b6',
    accentSoft: '#d4f7f3',
    art: 'prism',
  },
  {
    id: 'titan-trail',
    slug: 'titan-trail',
    name: 'Realm Clash',
    tagline: 'Build. Battle. Conquer.',
    description:
      'Command colorful armies, capture the central tower and conquer the rival realm with smart strategy.',
    guide: ['Coming soon.'],
    entryCost: ENTRY_COST,
    status: 'coming-soon',
    accent: '#d96c3b',
    accentSoft: '#ffe3d4',
    art: 'titan',
  },
];

export function getGameBySlug(slug: string): GameConfig | undefined {
  return GAMES.find((game) => game.slug === slug);
}

export const PLAYABLE_SLUGS = GAMES.filter((game) => game.status === 'playable').map(
  (game) => game.slug,
);
